version: '3.8'

services:
  backend:
    build:
      context: ./eco-task-backend
      dockerfile: Dockerfile
    ports:
      - "4000:3333"
    volumes:
      - ./eco-task-backend:/app
      - /app/node_modules
      - sqlite_data:/app/tmp  # Monte le dossier où est stockée la DB SQLite
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    networks:
      - eco-task

  frontend:
    build:
      context: ./eco-task-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./eco-task-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3333 # Utilise "backend" comme nom de service
    depends_on:
      - backend
    networks:
      - eco-task

volumes:
  sqlite_data:  # Volume pour persister la base SQLite

networks:
  eco-task:
