version: '3.8'

services:
  backend:
    build:
      context: ./eco-task-backend
      dockerfile: Dockerfile
    ports:
      - "4717:3333"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    networks:
      - eco-task

  frontend:
    build:
      context: ./eco-task-frontend
      dockerfile: Dockerfile
    ports:
      - "4718:3000"
    volumes:
      - ./eco-task-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://92.112.192.183:4717/api
      - backend
    networks:
      - eco-task

volumes:
  sqlite_data:

networks:
  eco-task: