version: '3.8'

services:
  backend:
    build:
      context: ./eco-task-backend
      dockerfile: Dockerfile
    ports:
      - "4717:3333"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - DB_CONNECTION=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_DATABASE=mydatabase
    env_file: ./eco-task-backend/.env
    networks:
      - backend-networks
      - public-networks
    depends_on:
      - db

  frontend:
    build:
      context: ./eco-task-frontend
      dockerfile: Dockerfile
    ports:
      - "4718:3000"
    volumes:
      - ./eco-task-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://92.112.192.183:4717/api
      - backend
    networks:
      - public-networks

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend-networks
    expose:
      - "5432"

volumes:
  pg_data:

networks:
  backend-networks:
    internal: true
  public-networks:
