import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Barre de navigation */}
        <nav className="bg-gray-900 text-white py-4 px-6 flex justify-between items-center">
          <h1 className="text-xl font-bold">Gestion de Projets</h1>
          <div className="space-x-4">
            <Link href="/formulaires" className="px-4 py-2 bg-blue-500 rounded hover:bg-blue-600">
              Formulaires
            </Link>
            <Link href="/kanban" className="px-4 py-2 bg-blue-500 rounded hover:bg-blue-600">
              Kanban
            </Link>
            <Link href="/dashboard" className="px-4 py-2 bg-blue-500 rounded hover:bg-blue-600">
              Dashboard
            </Link>
          </div>
        </nav>

        {/* Contenu principal */}
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
